[2024-12-08 16:35:19] [WARNING]: 签名服务器 http://localhost:8001/sign 可能不可用，请求出现错误：Get "http://localhost:8001/sign": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
[2024-12-08 16:35:19] [WARNING]: no usable sign server 
[2024-12-08 16:35:19] [WARNING]: 警告: 未配置签名服务器或签名服务器不可用, 这可能会导致登录 45 错误码或发送消息被风控 
[2024-12-08 16:35:25] [WARNING]: 恢复会话失败: exchange_emp failed: 16 , 尝试使用正常流程登录. 
[2024-12-08 16:35:39] [WARNING]: Protocol -> device lock is disabled. HTTP API may fail. 
[2024-12-08 16:35:50] [WARNING]: 上报 Event 数据到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2024-12-08 16:35:55] [WARNING]: 上报 Event 数据到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2024-12-08 16:35:59] [WARNING]: 上报 Event 数据到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2024-12-08 16:36:01] [WARNING]: 上报 Event 数据到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2024-12-08 16:36:05] [WARNING]: 上报 Event 数据到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2024-12-08 16:36:06] [WARNING]: 上报 Event 数据到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2024-12-08 16:36:07] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1733646945,"self_id":3759271832,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":35,"packet_sent":26,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2024-12-08 16:36:10] [WARNING]: 上报 Event 数据到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2024-12-08 16:36:11] [WARNING]: 上报 Event 数据到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2024-12-08 16:36:12] [WARNING]: 上报 Event 数据到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2024-12-08 16:36:16] [WARNING]: 上报 Event 数据 {"post_type":"notice","notice_type":"client_status","time":1733646954,"self_id":3759271832,"online":false,"client":{"app_id":537244899,"device_kind":"Android","device_name":"Android"}}
 到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2024-12-08 16:36:17] [WARNING]: 上报 Event 数据到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2024-12-08 16:36:17] [WARNING]: 上报 Event 数据到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2024-12-08 16:36:19] [WARNING]: 上报 Event 数据到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2024-12-08 16:36:23] [WARNING]: 上报 Event 数据 {"post_type":"message","message_type":"private","time":1733646961,"self_id":3759271832,"sub_type":"friend","raw_message":"都好好的","font":0,"sender":{"age":0,"nickname":"开挖9G","sex":"unknown","user_id":2279244533},"message_id":688705446,"user_id":2279244533,"target_id":3759271832,"message":"都好好的"}
 到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2024-12-08 16:36:23] [WARNING]: 上报 Event 数据到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2024-12-08 16:36:25] [WARNING]: 上报 Event 数据到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2024-12-08 16:36:29] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1733646967,"self_id":3759271832,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":44,"packet_sent":27,"packet_lost":0,"message_received":1,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":1733646961}},"interval":5000}
 到 http://localhost:5050/callback 失败: Post "http://localhost:5050/callback": dial tcp [::1]:5050: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
